name = "portfolio-construction"
main = "src/index.ts"
compatibility_date = "2025-08-15"
workers_dev = true

[vars]
BASE_URL = "http://127.0.0.1:8787"

# Override values for `--env production` usage
[env.production]
routes = [
	{ pattern = "farhanfadillah.com", custom_domain = true }
]

[env.production.vars]
BASE_URL = "https://farhanfadillah.com"
